apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-view
  namespace: dev
subjects:
- kind: ServiceAccount
  name: ken # Name is case sensitive
  namespace: dev
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io