apiVersion: v1
kind: Namespace
metadata:
  name: bob

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: bob

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-global
subjects:
- kind: ServiceAccount
  name: bob # Name is case sensitive
  namespace: bob
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io