apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-bg
  labels:
      app: payment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 100%
       maxUnavailable: 0%  
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: server
        image: sapunidze/hipster-shop-paymentservice:v0.0.2